import { test } from 'node:test';
import assert from 'node:assert/strict';
import { angleDistance, pointerAngle } from '../src/core/angle.js';
import { selectFrame, validateAngleMap } from '../src/core/frameSelector.js';
import { normalizeFrameSet } from '../src/core/avatarFrameSet.js';
import { ManualFrameProducer } from '../src/producers/manual.js';
import { normalizeVideoFrames } from '../src/producers/video/normalizeVideoFrames.js';
const map = validateAngleMap({version:1,center:{key:'center',src:'center.png'},directions:[{key:'e',src:'e.png',angle:3},{key:'s',src:'s.png',angle:80},{key:'w',src:'w.png',angle:211}]});
test('circular distance wraps through zero and negative angles',()=>{ assert.equal(angleDistance(359,1),2);assert.equal(angleDistance(-10,10),20); });
test('arbitrary uneven directions choose nearest with stable ties',()=>{ assert.equal(selectFrame(map,350,false).key,'e');assert.equal(selectFrame(map,160,false).key,'w');assert.equal(selectFrame(map,41.5,false).key,'e');assert.equal(selectFrame(map,211,true).key,'center'); });
test('dead zone uses shorter dimension and origin uses actual rect',()=>{const r={left:100,top:200,width:400,height:200};assert.equal(pointerAngle(300,300,r,.12).isCenter,true);assert.equal(pointerAngle(324,300,r,.12).isCenter,true);assert.equal(pointerAngle(325,300,r,.12).isCenter,false);assert.equal(pointerAngle(300,250,r,.12).angle,270);});
test('reject empty, duplicate and unsafe maps',()=>{for(const value of [{}, {...map,directions:[]},{...map,directions:[map.directions[0],map.directions[0]]},{...map,center:{key:'c',src:'../secret.png'}},{...map,directions:[{key:'n',src:'n.png',angle:NaN}]}])assert.throws(()=>validateAngleMap(value));});
test('AvatarFrameSet accepts arbitrary URLs and optional metadata',()=>{const frames=normalizeFrameSet({version:2,center:{key:'center',src:'https://cdn.example/avatar/center.webp'},directions:[{key:'left',src:'data:image/png;base64,AA==',angle:180}],metadata:{width:512,height:640,aspectRatio:.8,source:{type:'manual'}}});assert.equal(frames.center.src,'https://cdn.example/avatar/center.webp');assert.equal(frames.metadata?.source?.type,'manual');});
test('AvatarFrameSet rejects a missing center and supports legacy video normalization',()=>{assert.throws(()=>normalizeFrameSet({version:2,directions:[{key:'left',src:'left.png',angle:180}]}));const frames=normalizeVideoFrames(map);assert.equal(frames.version,2);assert.equal(frames.metadata?.source?.type,'video');});
test('manual producer passes synthetic photo-compatible frames through normalization',async()=>{const frames=await new ManualFrameProducer().generate(map);assert.equal(frames.center.key,'center');assert.equal(frames.version,2);});
