import type { AvatarStyleId } from './types.js';
export interface AvatarStyleDefinition { id: AvatarStyleId; version: 1; label: string; description: string; prompt: string; negativePrompt: string }
export const avatarStyles: Readonly<Record<AvatarStyleId, AvatarStyleDefinition>> = Object.freeze({
  'felt@1': { id: 'felt@1', version: 1, label: 'Handmade Felt', description: 'Warm handcrafted fibers and gentle detail.', prompt: 'Transform the subject into a handcrafted felt character with tactile wool fibers, softly rounded forms, and refined miniature craftsmanship.', negativePrompt: 'No text, watermark, extra people, distorted face, exaggerated body turn, or changed clothing.' },
  'cartoon@1': { id: 'cartoon@1', version: 1, label: 'Graphic Cartoon', description: 'Clean shapes, expressive features, and restrained shading.', prompt: 'Transform the subject into a polished graphic cartoon character with clean silhouettes, expressive but recognizable facial features, and restrained dimensional shading.', negativePrompt: 'No text, watermark, extra people, distorted anatomy, extreme caricature, or changed clothing.' },
  'cinematic-3d@1': { id: 'cinematic-3d@1', version: 1, label: 'Cinematic 3D', description: 'Detailed dimensional character with cinematic lighting.', prompt: 'Transform the subject into an original cinematic 3D character with refined materials, believable proportions, soft studio lighting, and high-quality dimensional detail.', negativePrompt: 'No studio-franchise imitation, text, watermark, extra people, facial distortion, strong body rotation, or changed clothing.' },
  'anime@1': { id: 'anime@1', version: 1, label: 'Modern Anime', description: 'Original anime-inspired portrait with controlled detail.', prompt: 'Transform the subject into an original modern anime-inspired character with clear linework, controlled cel shading, recognizable identity, and elegant facial detail.', negativePrompt: 'No named artist or franchise imitation, text, watermark, extra people, extreme expression, strong body rotation, or changed clothing.' }
});
export function getAvatarStyle(id: string): AvatarStyleDefinition { const style = avatarStyles[id as AvatarStyleId]; if (!style) throw new Error(`Unknown avatar style: ${id}`); return style; }
